---

- hosts: all
  become: true
  tasks:


  - name: create PP user
    user:
      name: PP
      groups: root 
    tags: PP
  
  - name: add ssh key for PP
    authorized_key:
      user: PP
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDhSjBPoki+Cqxf+Em8aUgAwXMJyiJS88yHw8r2PFIaKc0hYpmUpNOaQJkV9Nj1GnoVgiLvcPUCUzLrv0OKcZsYxg6hfEZFB0Gpg7UEzVAQBQPnPympe7ROBNeZyeKZS1rGhwavn9A99T4NvdMj9zYwcNdARwlOHnsaJDSW5AKCavOy1ijBHcd4WaB/kztUr4O5UIu6wvGEc5XcptCJMb6JCc2KgetXNX3mfZ1n911WkI1x6ke4y6n8UxsSaOpbO5qGdx3yrxek2ueKDZl5bLfRbtMBb9kCdH3ddGeR3aQHbsb6ij2ZRQKmUnphecDwpJQU7Xy2YcxLjOdyKf0u7lF5 root@c7a.domena7a.local"
    tags: PP

  - name: create sudoers file for PP
    copy:
      src: sudoers_PP
      dest: /etc/sudoers.d/PP
      owner: root
      group: root
      mode: 0440
    tags: PP

- hosts: all
  become: true
  tasks:

  - name: install updates (CentOS)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Mint)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Linux Mint"

  - name: install cowsay on Mint and CentOS
    package:
      name: cowsay
      state: latest
    tags: cowsay
    when: ansible_distribution in  ["CentOS", "Linux Mint"]

  - name: install unzip
    package:
      name: unzip
      state: latest
    when: ansible_distribution in  ["CentOS", "Linux Mint"]
    tags: unzip
  
  - name: install terraform from zip
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.2.7/terraform_1.2.7_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
    tags: terra

- hosts: [apache]
  become: true
  tasks:

  - name: install apache on CentOS
    yum:
      name: httpd
      state: latest
    tags: apache

  - name: change e-mail address for admin
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      regexp: "^ServerAdmin"
      line: ServerAdmin renouskovo@tektum
    when: ansible_distribution == "CentOS"
    tags: email


  - name: "run httpd service"
    service: 
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"
    tags: httpd.service

  - name: copy default html file for site
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644 
    tags: copy 

- hosts: [database]
  become: true
  tasks:

  - name: install mariaDB on Mint
    apt:
      name: mariadb-server
      state: latest
    tags: database





