---

- hosts: all
  become: true
  tasks:

  - name: install updates (CentOS)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Mint)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Linux Mint"

  - name: install cowsay on Mint and CentOS
    package:
      name: cowsay
      state: latest
    tags: cowsay
    when: ansible_distribution in  ["CentOS", "Linux Mint"]

- hosts: [apache]
  become: true
  tasks:

  - name: install apache on CentOS
    yum:
      name: httpd
      state: latest
    tags: apache

  - name: copy default html file for site
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644 
    tags: copy 

- hosts: [database]
  become: true
  tasks:

  - name: install mariaDB on Mint
    apt:
      name: mariadb-server
      state: latest
    tags: database





