---

- hosts: all
  become: true
  tasks:

  - name: uninstall updates (CentOS)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: uninstall updates (Mint)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Linux Mint"

  - name: uninstall cowsay on Mint and CentOS
    package:
      name: cowsay
      state: absent
    tags: cowsay


- hosts: [apache]
  become: true
  tasks:

  - name: uninstall apache on CentOS
    yum:
      name: httpd
      state: absent
    tags: apache


- hosts: [database]
  become: true
  tasks:

  - name: uninstall mariaDB on Mint
    apt:
      name: mariadb-server
      state: absent
    tags: database





